### ISSUE TITLE
crashes on both of my LG classic flip

### ISSUE THREAD

**Issue by LL-BB** [biden2020prez/CoolHome#1]

**Comment by LL-BB** [comment]
Hi. It's L-B from the apps4flip forums. Are there any known conflicts with other customizations that are popular for the LG Classic such as screen DPI? both versions of coolhome have the same issue of crashing on opening

**Comment by SZRabinowitz** [comment]
Hey, nice to hear from you. How are you? 

For coolhome, you must install using ADB install with -g so it gets installed with all permissions. I dont think screen dpi is an issue, I seem to recall having used it with lower screen DPI. Although it may not look good  on the screen, it shouln't crash i think. Try installing with -g and it shouldn't crash

**Comment by LL-BB** [comment]
Thank you I just set the permissions using ADB appcontrol and it worked!

**Comment by LL-BB** [comment]
Thank you for resolving the issue
